# Generated by Django 3.2.15 on 2022-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('left', models.IntegerField(null=True)),
                ('right', models.IntegerField(null=True)),
            ],
        ),
    ]
